main: com.solarrabbit.largeraids.LargeRaids
name: LargeRaids
version: '${project.version}'
author: SolarRabbit
api-version: 1.14

softdepend: [PlaceholderAPI, MythicMobs, Multiverse-Core]

commands:
  lrreload:
    description: Reloads LargeRaids plugin configurations.
    permission: largeraids.admin
  lrstart:
    description: Start a large raid at player location or given center.
    usage: /<command> [player | center] [name]
    permission: largeraids.admin
  lrstop:
    description: Stop a large raid.
    usage: /<command> [player]
    permission: largeraids.admin
  lrgive:
    description: Give a player the summoning item.
    usage: /<command> <player> [amount]
    permission: largeraids.admin
  lrcenters:
    description: Managing artificial villages.
    usage: /<command> [add | remove | show | hide] [name]
    permission: largeraids.admin
  lrglow:
    description: Outline all raiders in the current raid.
    permission: largeraids.glow

permissions:
  largeraids.admin:
    description: Allow access to LargeRaids commands.
    default: op
  largeraids.glow:
    description: Allow access to lrglow command.
    default: op
