name: "Auto-Compile"

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get Minecraft Version
        run: echo "MC_VERSION=$(gradlew -q getMCVersion)" >> $GITHUB_ENV

      - name: Get Plugin Version
        run: echo "PLUGIN_VERSION=$(gradlew -q getVersion)" >> $GITHUB_ENV

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: success()
        with:
          name: LargeRaids
          path: build/libs/

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.MC_VERSION }}"
          prerelease: false
          title: "Plugin Download for Minecraft ${{ env.MC_VERSION }}"
          files: |
            build/libs/LargeRaids-${{ env.PLUGIN_VERSION }}.jar
