name: "Compile"

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get Minecraft Version
        run: echo "MC_VERSION=$(${{ github.workspace }}/gradlew -q getMCVersion)" >> $GITHUB_ENV

      - name: Get Plugin Version
        run: echo "PLUGIN_VERSION=$(${{ github.workspace }}/gradlew -q getVersion)" >> $GITHUB_ENV

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LargeRaids
          path: build/libs/

      - name: Remove Old Tags
        run: gh release delete "${{ env.MC_VERSION }}" --cleanup-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ env.MC_VERSION }}"
          prerelease: false
          name: "Plugin Download for Minecraft ${{ env.MC_VERSION }}"
          files: |
            build/libs/LargeRaids-${{ env.PLUGIN_VERSION }}.jar
